### ISSUE TITLE
Vote down song

### ISSUE THREAD

**Issue by mykebates** [sgf-web-devs/tap-music#10]
No specifics on this yet.  Up for discussion, but the idea is simple.  If a room does not like a song then they can say so with their vote/thumb down/dislike, whatever.  A bunch of scenarios to think through on this one.

**Comment by fredlawl** [comment]
I think it would be silly to have the song stop playing if there's a lot of vote downs, but, would this vote down prevent the song from being queued ever again? At what point do we mark as the threshold? Maybe penalize a person for a little bit? 

I kinda don't want to have someone not be able to play their songs cause that defeats the purpose of collaborative music.

Thoughts? I think I'll go ahead and take charge of this enhancement.

**Comment by mykebates** [comment]
After some discussion we have decided to kill this feature off.
