### ISSUE TITLE
Configuration(s)

### ISSUE THREAD

**Issue by fredlawl** [sgf-web-devs/tap-music#16]
Allow index.js to accept the .evn.local.php configurations. Maybe it could be hacked together on the front end with some JS object like:

```javascript
var appConfig = {
    pusherKey = '<?php echo Config::get('services.pusher.app_key'); ?>'
};
```

**Comment by fredlawl** [comment]
Hmm... this appears to be fixed. Voooodoooo git merging!

**Comment by mykebates** [comment]
:+1:
