### ISSUE TITLE
Round-robin queue

### ISSUE THREAD

**Issue by mykebates** [sgf-web-devs/tap-music#7]
Right now, the way the queue handles is jank city.  It kind sorta works for the most part, but there are definitely some weird bugs with getting the sort order 100% accurate when a new song is added to the queue.  The queue should probably be reworked entirely while getting round-robin working.

**Comment by fredlawl** [comment]
Since we're kinda doing a personal queue that roundrobins to the main queue (what a mouth full), would this issue still be relevant?

**Comment by mykebates** [comment]
Correct-0
Closing
